library(tidyverse)
library(readxl)
library(ggeasy)
library("ggpubr")
library("sva")
#devtools::install_github("SaccoPerfettoLab/SignalingProfiler", lib = "/Users/veronicalombardi/Desktop/phd/PHD")
library(SignalingProfiler)
library(igraph)
library("stringr")
library(httr)
library(plyr)
library(pheatmap)
library(dendextend)
library(RColorBrewer)
library(broom)
library(GGally)
library(devtools)
library(ggfortify)
library(ggrepel)
library(tidyverse)
library(fgsea)
library(tibble)
library(readxl)
library(writexl)
library(tidyr)
library(readr)
library(cowplot)

